### ISSUE TITLE
Kill the spam link on the contrib repo

### ISSUE THREAD

**Issue by peterennis** [mojs-contrib/mojs#1]
and sign me up to contribute.

![capture553](https://user-images.githubusercontent.com/140737/51857279-aa824f80-22e6-11e9-9317-469d2566b12a.PNG)

Relates to: https://github.com/legomushroom/mojs/issues/201#issuecomment-447314391

**Comment by Sandstedt** [comment]
This repo is not maintained anymore. Please visit https://github.com/mojs-contrib for future developments.

**Comment by Sandstedt** [comment]
+1 For contribute. Else I do my best answering questions and guiding new people here.

**Comment by Sandstedt** [comment]
Created a pull request (don't have write access yet). Let's fix better links later.
#2

**Comment by xavierfoucrier** [comment]
Hi @peterennis!

No problem, I just send you the invite: welcome in the team :wink:

**Comment by peterennis** [comment]
@xavierfoucrier 
Invite accepted.
Thanks!
