### ISSUE TITLE
Linter for javascript

### ISSUE THREAD

**Issue by xavierfoucrier** [mojs-contrib/mojs#8]
Use the [eslint](https://github.com/eslint/eslint) linter with base rules in a `.eslintrc` file.

**Comment by Sandstedt** [comment]
Let's try and see how much of the code needs to be fixed. Could be a messy git history if all files will be changed. But maybe a necessary step to do.

**Comment by Sandstedt** [comment]
Have anyone trided using a githook and prettier to automatically format code when comitting new changes? Maybe this is a good format to ensure all code is correct regardless of ones editor? Saw this in the create-react-app startup documentation: https://facebook.github.io/create-react-app/docs/setting-up-your-editor

**Comment by xavierfoucrier** [comment]
@Sandstedt I haven't experienced with that for now :thinking: ...
